### ISSUE TITLE
Bottom navigation integration

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/VendorRelief#2]
Integrate bottom navigation in the application and make all required changes to it.

**Comment by riturajjain2000** [comment]
assign this to me!!

**Comment by spacemonkey1101** [comment]
is this issue still open?

**Comment by riturajjain2000** [comment]
@spacemonkey1101 you can work on it if you want, ask @plazzy99 to assign you to this.

**Comment by plazzy99** [comment]
> @spacemonkey1101 you can work on it if you want, ask @plazzy99 to assign you to this.

@spacemonkey1101 are you up for assigning this issue to yourself?

**Comment by spacemonkey1101** [comment]
ok i am taking this up

**Comment by plazzy99** [comment]
@spacemonkey1101 good to go 👍🏻 

remember you have to raise a pr in develop branch.
For any query, you can join the discord and ask me there 👍🏻
