### ISSUE TITLE
Kotlin - MVVM Transiton 

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [plazzy99/VendorRelief#27]
To convert the existing code base to **Kotlin** and  to restructure the code to follow **MVVM**  *(Model-View-VIewModel)* architectural pattern

The Goals are
1. **Move to Kotlin** : Kotlin being the official supported language for native Android development , it enables the user to write faster more concise code compared to java

2.  **MVVM Architectural Pattern** : The MVVM (Model-View-ViewModel) Patterns enables us to easily Separate UI, Data and Business Logic , thus making it easier to maintain code

3. **Use Android Architecture Components** : Android architecture components are a collection of libraries that help you design robust, testable, and maintainable apps ( E.g. Room, ViewModel, LiveData etc..)

**Comment by Vishwa-Raghavendra** [comment]
Can you please assign me this issue

**Comment by plazzy99** [comment]
@Vishwa-Raghavendra go ahead!!
