### ISSUE TITLE
Bottom navigation implementation for the signed in user.

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/VendorRelief#30]
Integrate bottom navigation in the application and make all required changes to it.

**Comment by Poornirt** [comment]
@plazzy99 I would like to work on it

**Comment by vatsalkesarwani12** [comment]
please start all your work in develop branch

**Comment by Poornirt** [comment]
Sure

**Comment by Poornirt** [comment]
Hi @plazzy99 bottom navigation is already implemented in develop branch. So I worked on checking internet connectivity before showing webview in corona spread fragment.
