### ISSUE TITLE
show all error messages in snackbar

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/VendorRelief#8]
currently errors are displayed using toast. You need to convert all toast for error message to snackbar.

**Comment by lucifer0987** [comment]
@plazzy99 Can you please assign me this issue?

**Comment by plazzy99** [comment]
> 
> 
> @plazzy99 Can you please assign me this issue?

You are good to go 👍🏻

**Comment by plazzy99** [comment]
@lucifer0987 raise a pr for this issue as it is 22days now.

**Comment by codeDamon** [comment]
@plazzy99 If the assignee is inactive, assign this issue to me. I can work on it.

**Comment by lucifer0987** [comment]
@plazzy99 yeah, please go ahead.

**Comment by plazzy99** [comment]
@codeDamon go ahead
