### ISSUE TITLE
Add loading dialog

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/VendorRelief#9]
Add a loading dialog when user clicks ```get vendor``` on home screen.
also add a delay of 2 sec.

**Comment by lucifer0987** [comment]
@plazzy99 Can you please assign me this issue?

**Comment by plazzy99** [comment]
> 
> 
> @plazzy99 Can you please assign me this issue?

You are good to go 👍🏻

**Comment by plazzy99** [comment]
@lucifer0987 this issue was inactive for too long and a pr was present so this issue is reassigned.

**Comment by plazzy99** [comment]
@codeDamon submit  the mentioned recording .
